name: CI

on: [push, pull_request]

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-rdma:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: build-rxe-kmod
        run: make rxe -j4
      - name: clear-dmesg
        run: sudo dmesg -c > /dev/null
      - name: install-kmod
        run: |
          sudo ./rdma_env.py -o setup -d rxe
          sudo lsmod
      - name: show-dmesg
        run: sudo dmesg -c > /dev/null
